const locationsList = [
  {
    list: "ciudad",
    data: [
      { city: "Madrid", country: "España" },
      { city: "Barcelona", country: "España" },
      { city: "Vigo", country: "España" },
      { city: "Valencia", country: "España" },
      { city: "Lisboa", country: "Portugal" },
      { city: "París", country: "Francia" },
      { city: "Londres", country: "Reino Unido" },
      { city: "Roma", country: "Italia" },
      { city: "Moscú", country: "Rusia" },
      { city: "Berlín", country: "Alemania" },
      { city: "Berna", country: "Suíza" },
      { city: "Bruselas", country: "Bélgica" },
    ],
  },
  {
    list: "playa",
    data: [
      { city: "Vigo", country: "España" },
      { city: "O Porto", country: "Portugal" },
      { city: "Marbella", country: "España" },
      { city: "Málaga", country: "España" },
      { city: "Valencia", country: "España" },
      { city: "Mallorca", country: "España" },
      { city: "Las Palmas de Gran Canaria", country: "España" },
      { city: "Ibiza", country: "España" },
      { city: "Funchal", country: "Portugal" },
      { city: "Barcelona", country: "España" },
      { city: "Marsella", country: "Francia" },
      { city: "Cancún", country: "México" },
    ],
  },
  {
    list: "historia",
    data: [
      { city: "Roma", country: "Italia" },
      { city: "Mérida", country: "España" },
      { city: "Jerusalén", country: "EsComplicado" },
      { city: "Damasco", country: "Siria" },
      { city: "Pompeya", country: "Italia" },
      { city: "Florencia", country: "Francia" },
      { city: "Londres", country: "Reino Unido" },
      { city: "París", country: "Italia" },
      { city: "Moscú", country: "Rusia" },
      { city: "Berlín", country: "Alemania" },
      { city: "Praga", country: "República Checa" },
      { city: "Bruselas", country: "Bélgica" },
    ],
  },
  {
    list: "isla",
    data: [
      { city: "Las Palmas de Gran Canaria", country: "España" },
      { city: "Mallorca", country: "España" },
      { city: "Santa Cruz de Tenerife", country: "España" },
      { city: "Lanzarote", country: "España" },
      { city: "Ibiza", country: "España" },
      { city: "Formentera", country: "España" },
      { city: "Menorca", country: "España" },
      { city: "Ajaccio", country: "Francia" },
      { city: "Sácer", country: "Italia" },
      { city: "Palermo", country: "Italia" },
      { city: "Heraclión", country: "Greacia" },
      { city: "Isla de Arousa", country: "España" },
    ],
  },
  {
    list: "montaña",
    data: [
      { city: "Oviedo", country: "España" },
      { city: "Barcelona", country: "España" },
      { city: "Vigo", country: "España" },
      { city: "La Alberca", country: "España" },
      { city: "Encamp", country: "Andorra" },
      { city: "Santa Cruz de Tenerife", country: "España" },
      { city: "Manzanares el Real", country: "España" },
      { city: "Ribadavia", country: "España" },
      { city: "Los Llanos", country: "España" },
      { city: "Cangas del Narcea", country: "España" },
      { city: "Berna", country: "Suíza" },
      { city: "Vaduz", country: "Liechtenstein" },
    ],
  },
  {
    list: "otros",
    data: [
      { city: "Albacete", country: "España" },
      { city: "Puerto Llano", country: "España" },
      { city: "El Ejido", country: "España" },
      { city: "O Porriño", country: "España" },
      { city: "Mos", country: "España" },
      { city: "Guarromán", country: "España" },
      { city: "Fuente Ovejuna", country: "España" },
      { city: "Teis", country: "España" },
      { city: "La Mojonera", country: "España" },
      { city: "Polopos", country: "España" },
      { city: "La Guapa", country: "España" },
      { city: "Motril", country: "España" },
    ],
  },
];
export default locationsList;
